### ISSUE TITLE
Irritating differences on mobile browsers

### ISSUE THREAD

**Issue by Pol74698** [opennoise1/p5-dialogue-generator#14]
Let me use Ann to describe the issues:

![Young woman-Text has different spacing on mobile_browsers compared to desktop_browsers..png](https://github.com/opennoise1/p5-dialogue-generator/assets/25173014/94d16787-dd24-44d1-ba09-de77418ca88e)

![Young woman-On some mobile browsers like Puffin,_the text spacing is correct, but the_text for certain long names is broken..png](https://github.com/opennoise1/p5-dialogue-generator/assets/25173014/720e2879-cb36-49b8-a50b-16be4b07be39)

**Comment by opennoise1** [comment]
Thanks for bringing this up! I'll look into it a little more, but unfortunately, from my experience, it seems that HTML Canvas (which is what displays the text and images, and allows for them to be downloaded) is just sort of buggy on certain browsers, which don't always fully support Canvas. That's why I have that message to try and direct people to use Chrome, which at least works consistently.
